# Generated by Django 4.1 on 2023-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=None, editable=False, max_length=88, unique=True
            ),
            preserve_default=False,
        ),
    ]
