# Generated by Django 4.0.8 on 2023-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Connect',
                'verbose_name_plural': 'Connects',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usersrule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersrule',
            name='updated_at',
        ),
    ]
