# Generated by Django 4.1 on 2023-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_article_photo_blogimages_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(default=None, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
