# Generated by Django 4.1 on 2023-11-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(default=None, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
