# Generated by Django 4.1 on 2023-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
