# Generated by Django 4.1 on 2023-11-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_article_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="date",
        ),
    ]
