# Generated by Django 4.1 on 2023-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_article_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="IpAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.ManyToManyField(blank=True, to="blog.ipaddress"),
        ),
    ]
