# Generated by Django 4.1 on 2023-11-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_options_course_average_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
