# Generated by Django 4.1 on 2023-11-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="in_process",
            new_name="in_process_watching",
        ),
    ]
